3405000/team201-backend

src/app.module.ts, src/users/entities/user-role.enum.ts, src/users/entities/user.entity.ts, src/users/users.controller.ts, src/users/users.module.ts, src/users/users.service.ts
- user 엔터티와 구성요소(서비스 컨트롤러 모듈) 생성했어요
- 피드백 요청
=> [feat] #1 - User entity 및 구성요소 생성

src/app.module.ts, src/config/typeorm.config.ts
- typeORM database config 파일 생성
- app module에 typeorm module import 적용
- 피드백 요청
=> [feat] #3 - typeORM DB 기본 설정

src/app.module.ts, src/stores/entities/store-category.enum.ts, src/stores/entities/store.entity.ts, src/stores/stores.controller.ts, src/stores/stores.module.ts, src/stores/stores.service.ts
=> [chore] #5 - store entity 및 구성요소 생성

src/app.module.ts, src/events/entities/event-status.enum.ts, src/events/entities/event.entity.ts, src/events/events.controller.ts, src/events/events.module.ts, src/events/events.service.ts
- event entity 및 구성요소 생성
- event-status.enum 정의가 안되어 있어서 임의로 만들었는데 검토 후 수정 필요
=> [chore] #7 - event entity 및 구성요소 생성

src/app.module.ts, src/reviews/entites/review.entity.ts, src/reviews/reviews.controller.ts, src/reviews/reviews.module.ts, src/reviews/reviews.service.ts
=> [feat] #11 Review & Comment 구성요소 생성 

src/app.module.ts, src/config/typeorm.config.ts
- app.module.ts 에서의 중복 호출 부분 삭제
- typeorm.config.ts 에서 엔터티 파일 위치 탐색 부분 코드 수정
=> [fix] #15 - typeorm.config, app.module 오류 수정

package-lock.json, package.json, src/app.module.ts, src/stores/DTO/create-store-request.dto.ts, src/stores/DTO/store-address-response.dto.ts, src/stores/DTO/store-response.dto.ts, src/stores/DTO/update-store-detail-requst.dto.ts, src/stores/entities/store.entity.ts, src/stores/stores.controller.ts, src/stores/stores.module.ts, src/stores/stores.service.ts
- store CRUD를 구현했어요
- 영찬이가 도와줬어요 (엔드포인트 통일 및 update 부분 수정)
=> [feat] #9 - store CRUD 구현

public/index.html, src/main.ts, src/maps/maps.controller.ts, src/maps/maps.module.ts, src/maps/maps.service.ts
closed #23 
<br/>
- 네이버 지도 Local API 연동
- 장소 검색 기능 API 구현
- API 호출 및 검색 결과 데이터 받아오기
- 검색 결과를 화면에 표시하는 뷰 개발
장소를 검색하면
이렇게 데이터를 받아온다
포스트맨으로도 확인이 가능하다
=> [feat] #23 - 장소 검색 기능 API 구현

package-lock.json, package.json, src/reviews/entites/review.entity.ts, src/reviews/reviews.controller.ts, src/reviews/reviews.service.ts
=> [feat] #29 - 리뷰 "도움됐어요" 기능 구현

package-lock.json, package.json, public/index.html
closed #28 
<br/>
- 사용자가 검색한 장소를 지도에 마커로 표시하는 기능 추가
- 검색 기능이 정상적으로 동작하는지 확인
- 여러 개의 마커가 정상적으로 추가되고 중복되지 않는지 확인
- 지도 확대/축소 및 이동 시 마커가 정상적으로 유지되는지 확인
- API 호출 시 오류 처리 확인 및 콘솔 오류 확인
=> [feat] #28 - 검색 장소 마커 표시 기능 추가

src/reviews/reviews.controller.ts
closed #46 
<br/>
- 테스트까지 야무지게 해놓고 오류 있는 버전으로 undo하고 pr함.
- 피드백 요청
=> [fix] #46 - 버그 수정

src/review-replies/DTO/create-reply.dto.ts, src/review-replies/DTO/read-all-replies.dto.ts, src/review-replies/DTO/upate-reply.dto.ts, src/review-replies/entities/review-reply.entity.ts, src/review-replies/review-replies.controller.ts, src/review-replies/review-replies.service.ts, src/reviews/DTO/read-all-reviews.dto.ts, src/reviews/reviews.controller.ts
closed #48 
<br/>
- Create를 제외한 Read, Update, Delete 기능 구현
- Create
---
- Read (1)
---
- Read(2)
---
- Update
---
- Delete
=> [feat] #48 - 매니저 대댓글 R, U, D 기능 구현

src/events/entities/event.entity.ts, src/review-replies/entities/review-reply.entity.ts, src/review-replies/review-replies.service.ts, src/reviews/entites/review.entity.ts, src/reviews/reviews.service.ts, src/store-requests/entities/store-request.entity.ts, src/stores/entities/store.entity.ts
closed #50 
<br/>
- 엔터티 간 연관관계 최적화
참조한 엔터티의 컬럼이 올바르게 DB에 나타나도록 코드 추가
---
- review_reply 작성 시 review테이블에 reply_id가 추가되도록 설정
- 피드백 요청
=> [refactor] #50 - 엔터티/DB 최적화

src/app.module.ts, src/manager-requests/DTO/create-manager-request.dto.ts, src/manager-requests/DTO/read-manager-request.dto.ts, src/manager-requests/DTO/update-manager-request.dto.ts, src/manager-requests/entities/manager-requests.entity.ts, src/manager-requests/manager-requests.controller.ts, src/manager-requests/manager-requests.module.ts, src/manager-requests/manager-requests.service.ts, src/store-requests/store-requests.module.ts
closed #42 
<br/>
- manager request 엔터티 및 dto 생성
- crud 구현
=> [feat] #42 - manager request 기능 구현

public/script.js, src/maps/maps.controller.ts, src/maps/maps.service.ts
closed #40 
<br/>
- 현재 위치를 쵸시하고, 이를 기준으로 주변 장소를 검색하는 기능 추가
- 전반적인 리팩토링 진행
- 일부 예외 처리 개선 및 검색 결과 필터링 추가
1. 현재 위치 표시 기능
- 현재 위치가 지도에서 정상적으로 마커에 표시되는지 확인
- 위치 권한 요청 팝업이 정상적으로 나타나는지 확인
- 위치 권한을 허용했을 때, 사용자의 정확한 위치가 표시되는지 확인
- 위치 권한을 거부한 경우 기본 위치가 표시되는지 확인
2. 주변 장소 검색 기능
- 현재 위치를 기준으로 주변 장소가 정상적으로 검색되는지 확인
- 검색 반경 내에서 장소가 필터링되는지 확인
- 검색된 주소 주변의 위치가 지도에 정상적으로 마커로 표시되는지 확인
3. 지도 정보창 관련
- 마커 클릭 시 infoWindow가 정상적으로 표시되는지 확인
- infoWindow의 내용이 올바르게 표시되는지 확인
4. 코드 리팩토링 검증
- window.onload : 실행 시점이 중복되지 않고 정상적으로 초기화되는지 확인 
- infoWindow : 생성 로직이 공통 함수로 분리되어 일관성이 유지되는지 확인
- mapConfig : 객체를 통한 전역 변수 관리가 정상적으로 이루어지는지 확인
- async/await : 변환 후 코드 실행이 올바르게 동작하는지 확인
- placeDetails : 함수가 중복된 API 요청을 방지하고 일관되게 동작하는지 확인
맨 처음 지도를 불러오면
위치 권한 요청 팝업이 표시되고
위치 권한을 허용하면 현위치 주변의 음식점을 마커로 표시해주고
허용하지 않을 …
=> [feat] #40 - 현재 위치 및 주변 장소 검색 기능 추가 및 코드 리팩토링

src/app.module.ts
=> [fix] #54 - app.module에 StoreRequest 모듈 추가

src/app.module.ts
=> [fix] #56 - app.module 중복 import 문제 해결

src/app.module.ts, src/events/events.service.ts, src/menus/DTO/create-menu.dto.ts, src/menus/DTO/read-all-menus.dto.ts, src/menus/DTO/read-menu.dto.ts, src/menus/DTO/update-menu.dto.ts, src/menus/entities/menu.entity.ts, src/menus/menus.controller.ts, src/menus/menus.module.ts, src/menus/menus.service.ts, src/stores/entities/store.entity.ts
closed #58 
<br/>
- 메뉴 엔터티 생성
- 메뉴 CRUD 구현
- CREATE
---
- READ[1] - 전체 메뉴 조회
---
- READ[2] - 특정 메뉴 조회
---
- UPDATE
---
- DELETE
=> [feat] #58 - menu 엔터티 및 CRUD 구현

src/common/api-reponse-dto/api-response.dto.ts, src/events/events.controller.ts, src/events/events.service.ts, src/manager-requests/manager-requests.controller.ts, src/manager-requests/manager-requests.service.ts, src/review-replies/review-replies.controller.ts, src/review-replies/review-replies.service.ts, src/reviews/reviews.controller.ts, src/reviews/reviews.service.ts, src/store-requests/store-requests.controller.ts, src/store-requests/store-requests.service.ts, src/stores/stores.controller.ts, src/stores/stores.service.ts
closed #60 
<br/>
- ApiResponseDTO 빠진 거 넣었어요
- Controller와 Service 전체적으로 다듬엇습니다
=> [refactor] ApiResponseDTO 적용, Controller와 Service 전체 수정

src/menus/menus.controller.ts, src/menus/menus.service.ts
closed #62 
<br/>
- Dto->DTO 로 변경하여 오류 수정
- 피드백 요청
=> [fix] #62 - 컨벤션 변경에 따른 menus폴더 오류 수정

src/main.ts
closed #65 
<br/>
프론트엔드에서 백엔드 API 호출 시 CORS 오류가 발생하여,
이를 해결하기 위한 CORS 설정 추가
- 프론트엔드에서 API 요청 정상 응답 확인 완료
=> [fix] #65 - CORS 설정 추가

src/store-requests/DTO/create-store-request.dto.ts, src/store-requests/DTO/read-store-request.dto.ts, src/store-requests/entities/store-request.entity.ts, src/store-requests/store-requests.module.ts, src/store-requests/store-requests.service.ts, src/users/entities/user.entity.ts, src/users/users.controller.ts, src/users/users.module.ts
closed #76 
<br/>
- StoreRequest와 User와의 관계형 설정, 나의 리뷰 조회 구현
=> [feat] #76 - StoreRequest 개선

src/stores/DTO/read-store.dto.ts
closed #80 
<br/>
- ReadStoreDTO에 latitude, longitude 추가
- 수정 내용
=> [fix] #80 - ReadStoreDTO latitude, longitude 누락 문제 수정

src/events/dto/create-event.dto.ts, src/events/events.controller.ts, src/events/events.service.ts, src/manager-requests/manager-requests.controller.ts, src/menus/DTO/create-menu.dto.ts, src/menus/menus.controller.ts, src/menus/menus.service.ts, src/reviews/reviews.controller.ts, src/store-requests/store-requests.controller.ts, src/stores/DTO/create-store.dto.ts, src/stores/entities/store.entity.ts, src/stores/stores.controller.ts, src/stores/stores.module.ts, src/stores/stores.service.ts, src/users/entities/user.entity.ts
=> [feat] #74 - Store페이지 구현(1)

src/stores/entities/store.entity.ts, src/stores/stores.service.ts, src/users/entities/user.entity.ts
closed #
<br/>
- merge 과정에서 발생한 conflict (중복 코드) 수정
- 피드백 요청
=> [fix] merge conflict 수정

src/events/dto/read-all-events.dto.ts, src/events/dto/read-event.dto.ts, src/events/dto/update-event.dto.ts, src/events/entities/event.entity.ts, src/events/events.controller.ts, src/events/events.service.ts
=> [feat] #88 - Store 페이지 구현 (2)

src/events/dto/update-event.dto.ts, src/events/events.controller.ts, src/events/events.service.ts
=> [refactor] #90 - 반영 안된 변경사항 commit

src/users/users.controller.ts, src/users/users.service.ts
closed #92 
<br/>
- 프론트엔드 52번 PR 구현을 위한 코드 추가
[https://github.com/3405000/team201-frontend/pull/52]
- 피드백 요청
=> [feat] #92 - 회원가입 기능 구현

src/reviews/DTO/create-review.dto.ts, src/reviews/reviews.controller.ts, src/reviews/reviews.service.ts, src/stores/stores.controller.ts
closed #94 
<br/>
- 가게 리뷰 작성 기능 관련해 storesService로 이사했어요
- storeId를 dto가 아닌 param으로 받도록 변경했어요
=> [refactor] #94 - review service, controller, dto 수정

src/stores/DTO/read-store.dto.ts, src/stores/entities/store.entity.ts, src/stores/stores.controller.ts, src/stores/stores.service.ts, src/users/entities/user.entity.ts
closed #96 
<br/>
- 해당 매니저의 store 목록 불러오기 기능 구현 완료
- **주제 변경 이슈로 작업 일시 중단**
- 피드백 요청
=> [feat] #96 - 가게 정보 수정 기능 구현 (중단)

src/auth/auth.controller.ts, src/common/custom-decorators/custom-role.guard.ts, src/common/custom-decorators/get-user.decorator.ts, src/common/custom-decorators/roles.decorator.ts, src/events/events.controller.ts, src/manager-requests/manager-requests.controller.ts, src/maps/maps.controller.ts, src/menus/menus.controller.ts, src/replies/replies.controller.ts, src/reviews/reviews.controller.ts, src/store-requests/store-requests.controller.ts, src/stores/stores.controller.ts, src/users/users.controller.ts
closed #100 
<br/>
https://github.com/3405000/team201-frontend/pull/63
- 위 기능을 구현하기 위한 AuthGuard, UseGuard 구현
- 피드백 요청
=> [feat] #100 - AuthGuard, UseGuard 구현

src/app.module.ts, src/favorites/DTO/create-favorite.dto.ts, src/favorites/DTO/read-favorite.dto.ts, src/favorites/entites/favorite.entity.ts, src/favorites/favorites.controller.ts, src/favorites/favorites.module.ts, src/favorites/favorites.service.ts, src/stores/entities/store.entity.ts, src/users/entities/user.entity.ts
closed #102 
<br/>
- Favorite Entity 생성 (User, Store와 N:1 관계 설정, 복합키 구성)
- CreateFavoriteDTO, ReadFavoriteDTO 정의
- FavoritesController 작성
- FavoritesService: 즐겨찾기 추가, 조회, 삭제 기능 구현
버튼을 누르면 삭제가 가능하다.
=> [feat] #102 - 즐겨찾기 기능 구현

src/stores/DTO/create-store.dto.ts, src/stores/DTO/read-store-address.dto.ts, src/stores/DTO/read-store.dto.ts, src/stores/entities/store.entity.ts
closed #106 
<br/>
- 위도/경도 컬럼 타입을 bigint(string)으로 변경하여 정밀도 보장
- 읍/면/동 정보 저장용 area 컬럼 추가
- 관련 DTO 및 서비스 코드 타입 변경
- 피드백 요청
=> [feat] #106 - area 컬럼 추가 및 위도/경도 bigint로 변경

src/maps/maps.controller.ts
closed #114 
<br/>
- 지도 관련 API 요청에 JWT 인증을 적용하여 인증된 사용자만 접근 가능하도록 처리
- Roles Guard를 적용하여 사용자 권한(role)에 따라 지도 API 접근을 제어
- 피드백 요청
=> [feat] #114 - 지도 API JWT 인증 및 roles guard 적용

src/maps/maps.controller.ts, src/maps/maps.module.ts, src/maps/maps.service.ts
closed #111 
<br/>
- 사용자의 현위치 좌표(latitude, longitude) 를 기준으로 일정 반경 내 주변 가게 목록을 조회하는 API 추가
- 거리 기반 필터링 로직 구현 및 거리 정보 포함 응답 제공
- 클라이언트에서 위치 기반 지도 탐색 기능과 연동될 수 있도록 API 응답 구조 설계
- 피드백 요청
=> [feat] #111 - 현위치 기준 주변 가게 조회 API 추가

src/categories/categories.module.ts, src/categories/categories.service.ts, src/categories/entities/category.entity.ts, src/stores/DTO/create-store.dto.ts, src/stores/DTO/read-store.dto.ts, src/stores/DTO/update-store-detail.dto.ts, src/stores/entities/store.entity.ts, src/stores/stores.controller.ts, src/stores/stores.module.ts, src/stores/stores.service.ts
closed #119 
<br/>
StoreService에서 직접 CategoryRepository에 접근하던 기존 구조를 개선하여, CategoriesService를 주입받아 간접적으로 카테고리 데이터를 조회하도록 변경
- 피드백 요청
=> [refactor] category 타입을 객체로 변경하고 관련 로직 수정

src/app.module.ts
closed #122 
<br/>
- appModule에 eventController 추가
- 피드백 요청
=> [fix] appModule에 eventController 추가

src/common/custom-decorators/custom-role.guard.ts, src/events/events.controller.ts, src/manager-requests/manager-requests.controller.ts, src/store-requests/store-requests.controller.ts, src/stores/stores.controller.ts, src/stores/stores.service.ts
closed #124 
<br/>
- 이벤트와 점주신청서에 logginedUser 적용
- 가게 검색 기능 구현
- 피드백 요청
=> [feat] #124 - Event, ManagerRequest LogginedUser 적용, Search 기능 구현

src/events/DTO/create-event.dto.ts, src/events/DTO/update-event.dto.ts
closed #136 
<br/>
- 프론트에서 Date 데이터가 JSON 형식으로 백으로 넘어올 때, string 타입으로 변환되어 정상적으로 인식되지 않는 문제 해결 -> string 타입으로 전달받은 데이터를 Date 객체로 변환해 저장
- 생성 및 수정 잘되어요
=> [fix] #136 - 날짜 정보 Date 타입으로 변환

src/file/file.service.ts
closed #141 
<br/>
- **.env 추가사항 있으니 반영해주세요!** 
- S3 대신 CloudFront를 사용하여 public / private 파일을 구분하여 동작하도록 설정
- 현재 RDS 데이터베이스를 사용하는 구조라 유저 정보와 가맹점 정보가 없어 테스트 할 수 없습니다.
- 나중에 DB에 유저와 가맹점 등을 설정해놓은 뒤 테스트 필요
- 피드백 요청
=> [refactor] #141 - S3 -> CloudFront 대체

src/stores/DTO/update-store-detail.dto.ts
=> [feat] #143 - 가맹점 설명을 필수요소가 아니도록 변경

src/maps/maps.service.ts
closed #145 
<br/>
- 기존: category_id, category_name → 평면 구조
- 수정: { category: { category_id, category_name } } 구조로 가공하여 반환
- latitude, longitude 필드명 통일
- 피드백 요청
=> [fix] #145 - 주변 가게 조회 응답 구조 개선

src/stores/stores.controller.ts
closed #147 
<br/>
- 비로그인 사용자도 지도에서 장소를 검색할 수 있도록 접근 권한 변경
- @Public() 데코레이터를 모든 가게 조회 API에 추가
- 피드백 요청
=> [feat] #147 - 비로그인 상태에서도 장소 검색 가능하도록 @Public() 추가

src/file/entities/file.entity.ts, src/file/entities/upload-type.enum.ts, src/file/file.service.ts, src/reviews/DTO/read-review.dto.ts, src/reviews/reviews.service.ts, src/users/DTO/read-user.dto.ts, src/users/DTO/update-user.dto.ts, src/users/entities/user.entity.ts, src/users/users.controller.ts, src/users/users.module.ts, src/users/users.service.ts
=> [feat] #149 - 프로필 사진 설정 기능 추가

src/auth/auth.service.ts, src/auth/interfaces/authenticated-request.interface.ts, src/auth/interfaces/jwt-payload.interface.ts, src/auth/strategies/jwt.strategy.ts
=> [feat] #151 - JWT토큰에 사용자 프로필 이미지 추가

src/openai/openai.controller.ts, src/openai/openai.service.ts
closed #153 
<br/>
- POST /api/openai/keywords 엔드포인트 구현
- 사용자 프롬프트를 받아 ai로 음식 관련 키워드 3개 생성
- 응답 형식: { keywords: string[] }
- 피드백 요청
=> [feat] #153 - OpenAI 추천 키워드 생성 API 추가

src/reviews/DTO/read-review.dto.ts, src/reviews/my-reviews.controller.ts, src/reviews/reviews.controller.ts, src/reviews/reviews.module.ts
=> [refactor] #156 - 내 리뷰 조회 컨트롤러 분기
